title: Apuntes de PowerShell
description: > # this means to ignore newlines until "baseurl:"
  Apuntes de PowerShell elaborados por Sergio Rey, profesor
  de ciclos formativos en el I.E.S. Lluis Simarro Laclabra 
  (Xàtiva, Valencia)
baseurl: "/powershell" # the subpath of your site, e.g. /blog
url: "http://iso.sergio-rey.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown